require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ScorecardSheetsController do

  # This should return the minimal set of attributes required to create a valid
  # ScorecardSheet. As you add validations to ScorecardSheet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "total" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ScorecardSheetsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all scorecard_sheets as @scorecard_sheets" do
      scorecard_sheet = ScorecardSheet.create! valid_attributes
      get :index, {}, valid_session
      assigns(:scorecard_sheets).should eq([scorecard_sheet])
    end
  end

  describe "GET show" do
    it "assigns the requested scorecard_sheet as @scorecard_sheet" do
      scorecard_sheet = ScorecardSheet.create! valid_attributes
      get :show, {:id => scorecard_sheet.to_param}, valid_session
      assigns(:scorecard_sheet).should eq(scorecard_sheet)
    end
  end

  describe "GET new" do
    it "assigns a new scorecard_sheet as @scorecard_sheet" do
      get :new, {}, valid_session
      assigns(:scorecard_sheet).should be_a_new(ScorecardSheet)
    end
  end

  describe "GET edit" do
    it "assigns the requested scorecard_sheet as @scorecard_sheet" do
      scorecard_sheet = ScorecardSheet.create! valid_attributes
      get :edit, {:id => scorecard_sheet.to_param}, valid_session
      assigns(:scorecard_sheet).should eq(scorecard_sheet)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ScorecardSheet" do
        expect {
          post :create, {:scorecard_sheet => valid_attributes}, valid_session
        }.to change(ScorecardSheet, :count).by(1)
      end

      it "assigns a newly created scorecard_sheet as @scorecard_sheet" do
        post :create, {:scorecard_sheet => valid_attributes}, valid_session
        assigns(:scorecard_sheet).should be_a(ScorecardSheet)
        assigns(:scorecard_sheet).should be_persisted
      end

      it "redirects to the created scorecard_sheet" do
        post :create, {:scorecard_sheet => valid_attributes}, valid_session
        response.should redirect_to(ScorecardSheet.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved scorecard_sheet as @scorecard_sheet" do
        # Trigger the behavior that occurs when invalid params are submitted
        ScorecardSheet.any_instance.stub(:save).and_return(false)
        post :create, {:scorecard_sheet => { "total" => "invalid value" }}, valid_session
        assigns(:scorecard_sheet).should be_a_new(ScorecardSheet)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ScorecardSheet.any_instance.stub(:save).and_return(false)
        post :create, {:scorecard_sheet => { "total" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested scorecard_sheet" do
        scorecard_sheet = ScorecardSheet.create! valid_attributes
        # Assuming there are no other scorecard_sheets in the database, this
        # specifies that the ScorecardSheet created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ScorecardSheet.any_instance.should_receive(:update).with({ "total" => "1" })
        put :update, {:id => scorecard_sheet.to_param, :scorecard_sheet => { "total" => "1" }}, valid_session
      end

      it "assigns the requested scorecard_sheet as @scorecard_sheet" do
        scorecard_sheet = ScorecardSheet.create! valid_attributes
        put :update, {:id => scorecard_sheet.to_param, :scorecard_sheet => valid_attributes}, valid_session
        assigns(:scorecard_sheet).should eq(scorecard_sheet)
      end

      it "redirects to the scorecard_sheet" do
        scorecard_sheet = ScorecardSheet.create! valid_attributes
        put :update, {:id => scorecard_sheet.to_param, :scorecard_sheet => valid_attributes}, valid_session
        response.should redirect_to(scorecard_sheet)
      end
    end

    describe "with invalid params" do
      it "assigns the scorecard_sheet as @scorecard_sheet" do
        scorecard_sheet = ScorecardSheet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ScorecardSheet.any_instance.stub(:save).and_return(false)
        put :update, {:id => scorecard_sheet.to_param, :scorecard_sheet => { "total" => "invalid value" }}, valid_session
        assigns(:scorecard_sheet).should eq(scorecard_sheet)
      end

      it "re-renders the 'edit' template" do
        scorecard_sheet = ScorecardSheet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ScorecardSheet.any_instance.stub(:save).and_return(false)
        put :update, {:id => scorecard_sheet.to_param, :scorecard_sheet => { "total" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested scorecard_sheet" do
      scorecard_sheet = ScorecardSheet.create! valid_attributes
      expect {
        delete :destroy, {:id => scorecard_sheet.to_param}, valid_session
      }.to change(ScorecardSheet, :count).by(-1)
    end

    it "redirects to the scorecard_sheets list" do
      scorecard_sheet = ScorecardSheet.create! valid_attributes
      delete :destroy, {:id => scorecard_sheet.to_param}, valid_session
      response.should redirect_to(scorecard_sheets_url)
    end
  end

end
